Title:   You can take the calendar with you when you go...
Package: WWW::AdventCalendar

=head1 Merry Christmas!  Advent is over.

It's a common misconception that Advent calendars include today, Christmas Day,
but traditionally they stop yesterday on the 24th.  Still, who am I to argue
with the Perl Advent Calendar traditions?  Here's my compromise: today, I'll
just give you the calendar itself: L<WWW::AdventCalendar>.

=head1 In which our author fails to steal from his peers...

On November 18th, I decided it might be fun to write a series of Advent
Calendar articles for just my own code, published along side the other
calendars.  I asked one or two people if they thought this was a terrible idea,
and they said it was not, so I decided I'd better get to work as quickly as
possible.  That means not worrying about writing any software to produce the
article, but just to write articles.  I would steal someone else's code!

First, I looked for whatever powered the L<Perl Advent
Calendar|http://perladvent.org>.  I figured with new CSS it would be fine.  I
found L<Pod::Advent>, but something about it made me decide to keep looking.  I
have no idea what anymore.  Then I went to CatalystAdvent, which powers the L<Catalyst Advent Calendar|http://www.catalystframework.org/calendar>.  I liked its look out of the box, so I started to install it, but it needed things no longer on CPAN.  I hacked around that and then started to wonder whether I wouldn't be happier just publishing static files.  Why?  Who knows.

I try pretty hard not to re-invent solutions to solved problems, and (believe
it or not) I succeed more often than not in quashing my urge to rewrite
perfectly good systems.  Here, though, it seemed like I'd be happier with
something I wrote for myself.  In the end, I think I was.

Anyway, I mostly stole the CSS and templates from Catalyst, and I'm pretty
happy that, too.

=head1 WWW::AdventCalendar

WWW::AdventCalendar is, as you might expect, pretty stupidly simple.  Right now
it only works for Advent, although I'd like to make it better at doing longer
spans of time.  Could I use a "real" blogging system for this?  Yes.  Am I
likely to?  No.

There's just a program to run that looks for your articles, decides how many to
publish, and writes out the article HTML, the index, the Atom feed, and a few
other files.

  ~/code/advent$ ./bin/advcal --today 2009-12-11 --articles ./rjbs/articles/  
  processing article for 2009-12-01...
  processing article for 2009-12-02...
  processing article for 2009-12-03...
  processing article for 2009-12-04...
  processing article for 2009-12-05...
  processing article for 2009-12-06...
  processing article for 2009-12-07...
  processing article for 2009-12-08...
  processing article for 2009-12-09...
  processing article for 2009-12-10...
  processing article for 2009-12-11...

The input files are Pod documents where the non-pod content is an email
document.  Alternately, the input files are email documents where the body is
Pod.  I<What??>  Well:

  Title:   You can take the calendar with you when you go...
  Package: WWW::AdventCalendar

  =head1 Merry Christmas!  Advent is over.

  It's a common misconception that Advent calendars include today, Christmas
  Day,

I originally made the body markup type pluggable, but then I remembered how
much I love Pod and I dropped that feature.  This let me use one set of syntax
semantics for everything.  For example, I could write:

  =begin vim lisp

  (format nil "~4,'0d-~2,'0d-~2,'0d" 2005 6 10) ; ==> 2005-06-10
  (format nil "~:(~a~)" "tHe Quick BROWN foX")  ; ==> "The Quick Brown Fox"
  (format nil "~:r" 1234)  ; ==> "one thousand two hundred thirty-fourth"
  (format nil "~:@r" 1234) ; ==> "MCCXXXIIII"

  =end vim

...and get some nicely colorized Lisp code.  (The color scheme, by the way, is
based on L<my Vim
colorscheme|http://www.vim.org/scripts/script.php?script_id=260>.  The code
uses L<Vim|Text::VimColor> (the editor) to colorize my code, but for Perl I
decided to use L<PPI::HTML>, which was faster and had a bit more control.  I
could just write L<=begin perl> but that got tedious, so I added another
transformation so that by writing...

=begin vim text

  but that got tedious, so I added another transformation so that by writing...

    #!perl
    my $x = { foo => 10 };

=end vim

The indented block's shebang would be noticed, and instead I'd get:

  #!perl
  my $x = { foo => 10 };

=head1 The Pod Transformers

So, those bits of code are the useful bits, unless you really want to run an
advent calendar just like me.  For now they're being released with
WWW::AdventCalendar, because they're just a bit too hacky to be for general use
yet, I think.  Still, here's what they do:

I'm using L<Pod::Xhtml> to convert from Pod to HTML.  It's not bad, although
I'll probably switch to L<Pod::Simple::XHTML> in the future.  Either way, I can
have a C<=begin xhtml> block that lets me provide literal XHTML rather than
Pod.  This is perfect for providing marked up, colorized code blocks.  All I
had to do was get those XHTML blocks produced before Pod::Xhtml did its thing.

Obviously, this was a job for L<Pod::Elemental>, the engine behind
L<Pod::Weaver>!  I wrote two libraries, L<Pod::Elemental::Transformer::PPIHTML>
and L<Pod::Elemental::Transformer::VimHTML>, both of which composed the
L<Pod::Elemental::Transformer::SynHi> role.  All that left for the transformers
to do was have a method that picked which parts of the document to rewrite and
then another that returned the newly built HTML.

I'm hoping that these will make it easy to write other syntax highlighting
engines for Pod-to-HTML conversion in the future -- possibly engines that dont'
require spawning F<vim> instances!

=head1 Same Code Next Year

I'll definitely be using this code again next year... if I decide to try to
repeat this undertaking, which is a big if.  I'm hoping to make the syntax
stuff a useful tool for other projects, and I really want to make the advent
calendar work across arbitrary date ranges.  Still, it was fun to write, easy
to use, and I hope somebody else gets some kind of benefit from it in the
future.

Until then... Merry Christmas!

=head1 See Also

=for wikidoc
* [WWW::AdventCalendar]
* [Pod::Advent] - the Pod formatter used by L<http://perladvent.org> (not me)
* [CatalystAdvent|http://dev.catalyst.perl.org/repos/Catalyst/trunk/examples/CatalystAdvent/] - the Catalyst Advent Calendar, whose CSS I stole
* [Text::VimColor] - colorize any syntax type that Vim understands
* [PPI::HTML] - turn Perl into syntax marked HTML with [PPI]
